#!/boot/common/bin/python
import BApplication
from BRoster import be_roster

class App(BApplication.BApplication):
	def __init__(self):
		BApplication.BApplication.__init__(self, 'application/x-stuff')
	def ReadyToRun(self):
		be_roster.Launch('application/x-vnd.Be-NPOS', ['/boot/home/public_html/index.html'])
		self.Quit()

w = App()
w.Run()
